### ISSUE TITLE
missing library when opening Shor's Algorithm in IBM Quantum Experience

### ISSUE THREAD

**Issue by johannesgreiner** [qiskit-community/qiskit-textbook#733]
**Describe the bug**
following https://quantum-computing.ibm.com/jupyter/user/qiskit-textbook/content/ch-algorithms/shor.ipynb
and running the first cell returns a missing library error

**To Reproduce**
1. Go to https://qiskit.org/textbook/ch-algorithms/shor.html
2. Click on 'Open in IBM Quantum Experience'
3. run first cell

**Expected behavior**
module is expected to load

**Screenshots**
![image](https://user-images.githubusercontent.com/70909228/92406537-8c263c00-f138-11ea-9b63-9bffdc162030.png)

**Additional context**
ModuleNotFoundError: No module named 'tabulate'

**Comment by abhobe** [comment]
This has been fixed. You can close this issue now.

**Comment by johannesgreiner** [comment]
@abhobe no I still get the same error when opening https://quantum-computing.ibm.com/jupyter/user/qiskit-textbook/content/ch-algorithms/shor.ipynb and running the first cell. What do you think has been fixed? Do you not get this error when opening exactly this link and running the first cell? please provide a screenshot and more details. error still persists.

**Comment by frankharkins** [comment]
This has not been fixed. We need to rewrite the chapter to remove use of `tabulate`, I think we can do this while keeping the neat alignment using `.ljust() / .rjust()` and/or`.format()` (see examples [here](https://stackoverflow.com/a/39032993/6441745) and [here](https://stackoverflow.com/a/43244749/6441745)).

**Comment by abhobe** [comment]
Whoops my bad. I ran some other code and it fixed the issue.

**Comment by johannesgreiner** [comment]
thanks @vabarbosa & @frankharkins ! Great to see it fixed
