### ISSUE TITLE
Quick exercise question numbers in Phase Kickback Chapter

### ISSUE THREAD

**Issue by Jwala-1908** [qiskit-community/qiskit-textbook#788]
**Describe the issue**
All of "Quick Exercise" questions at the end of Phase Kickback (Chapter 2.3) are numbered "1".

**Describe what you expect to see**
1,2,3

**Comment by paniash** [comment]
Thank you for pointing this out. The issue is already fixed and will be later synced with the website.

**Comment by Jwala-1908** [comment]
Oh okay!

**Comment by frankharkins** [comment]
@paniash unfortunately this was not fixed. The lists appeared correctly in the notebooks but not when rendered to the site. I have provided a fix in #790
